spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/strataforge
spring.datasource.username=strataforge
spring.datasource.password=strataforge_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
